import json
import logging
from typing import Any, Dict, List

from fastapi import HTTPException
from fastapi import status

from app.ai.llm_client import LLMClient
from app.config import settings
from app.repositories.learning_roadmap_repo import LearningRoadmapRepository
from app.repositories.resume_repo import ResumeRepository


logger = logging.getLogger(__name__)


class LearningRoadmapService:
    """
    Service layer for Learning Roadmap generation.

    Responsibilities:
    - Validate resume ownership
    - Validate resume extracted text
    - Call LLMClient to generate roadmap
    - Normalize LLM response safely
    - Save roadmap report in database
    - Retrieve, search, update, delete reports
    """

    def __init__(self, db) -> None:
        self.resume_repo = ResumeRepository(db)
        self.roadmap_repo = LearningRoadmapRepository(db)

    def generate_learning_roadmap(
        self,
        user_id: int,
        resume_id: int,
        target_role: str,
        provider: str | None = None,
        model_name: str | None = None,
    ) -> Dict[str, Any]:
        """
        Generate and persist a personalized AI learning roadmap.
        """

        resume = self.resume_repo.get_resume_by_id(
            resume_id=resume_id,
            user_id=user_id,
        )

        if not resume:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Resume not found",
            )

        resume_text = (resume.extracted_text or "").strip()

        if not resume_text:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Resume does not contain extracted text",
            )

        cleaned_target_role = target_role.strip()

        if not cleaned_target_role:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Target role cannot be empty",
            )

        final_provider = provider or settings.LLM_PROVIDER
        final_model_name = model_name or settings.LLM_MODEL

        llm_client = LLMClient(
            provider=final_provider,
            model_name=final_model_name,
        )

        roadmap = llm_client.generate_learning_roadmap(
            resume_text=resume_text,
            target_role=cleaned_target_role,
        )

        if not isinstance(roadmap, dict):
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Invalid learning roadmap response generated by LLM",
            )

        roadmap_title = self._to_text(
            roadmap.get(
                "roadmap_title",
                f"{cleaned_target_role} Learning Roadmap",
            )
        )

        if not roadmap_title:
            roadmap_title = f"{cleaned_target_role} Learning Roadmap"

        roadmap_data = {
            "user_id": user_id,
            "resume_id": resume.id,
            "target_role": cleaned_target_role,
            "current_skills": self._to_text(
                roadmap.get("current_skills")
            ),
            "missing_skills": self._to_text(
                roadmap.get("missing_skills")
            ),
            "roadmap_title": self._limit_text(
                roadmap_title,
                255,
            ),
            "roadmap_summary": self._to_text(
                roadmap.get("roadmap_summary")
            ),
            "weekly_plan": self._to_text(
                roadmap.get("weekly_plan")
            ),
            "recommended_projects": self._to_text(
                roadmap.get("recommended_projects")
            ),
            "recommended_courses": self._to_text(
                roadmap.get("recommended_courses")
            ),
            "recommended_certifications": self._to_text(
                roadmap.get("recommended_certifications")
            ),
            "priority_topics": self._to_text(
                roadmap.get("priority_topics")
            ),
            "estimated_duration": self._to_text(
                roadmap.get("estimated_duration")
            ),
            "provider": self._limit_text(
                final_provider,
                50,
            ),
            "model_name": self._limit_text(
                final_model_name,
                255,
            ),
        }

        saved_roadmap = self.roadmap_repo.create_roadmap(
            roadmap_data
        )

        logger.info(
            "Learning roadmap generated successfully | user_id=%s resume_id=%s roadmap_id=%s",
            user_id,
            resume_id,
            saved_roadmap.id,
        )

        return self._serialize_roadmap(
            saved_roadmap
        )

    def get_roadmap(
        self,
        roadmap_id: int,
        user_id: int,
    ) -> Dict[str, Any]:
        """
        Get one roadmap report by ID.
        """

        roadmap = self.roadmap_repo.get_roadmap_by_id(
            roadmap_id=roadmap_id,
            user_id=user_id,
        )

        if not roadmap:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Learning roadmap not found",
            )

        return self._serialize_roadmap(
            roadmap
        )

    def get_my_roadmaps(
        self,
        user_id: int,
        skip: int = 0,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """
        Get paginated roadmap reports for logged-in user.
        """

        roadmaps = self.roadmap_repo.get_roadmaps_by_user(
            user_id=user_id,
            skip=skip,
            limit=limit,
        )

        return [
            self._serialize_roadmap(roadmap)
            for roadmap in roadmaps
        ]

    def search_roadmaps(
        self,
        user_id: int,
        search: str,
        skip: int = 0,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """
        Search roadmap reports.
        """

        cleaned_search = search.strip()

        if not cleaned_search:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Search query cannot be empty",
            )

        roadmaps = self.roadmap_repo.search_roadmaps(
            user_id=user_id,
            search=cleaned_search,
            skip=skip,
            limit=limit,
        )

        return [
            self._serialize_roadmap(roadmap)
            for roadmap in roadmaps
        ]

    def get_roadmaps_by_target_role(
        self,
        user_id: int,
        target_role: str,
        skip: int = 0,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """
        Filter roadmap reports by target role.
        """

        cleaned_target_role = target_role.strip()

        if not cleaned_target_role:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Target role cannot be empty",
            )

        roadmaps = self.roadmap_repo.get_roadmaps_by_target_role(
            user_id=user_id,
            target_role=cleaned_target_role,
            skip=skip,
            limit=limit,
        )

        return [
            self._serialize_roadmap(roadmap)
            for roadmap in roadmaps
        ]

    def update_roadmap(
        self,
        roadmap_id: int,
        user_id: int,
        update_data: dict,
    ) -> Dict[str, Any]:
        """
        Update learning roadmap metadata.
        """

        roadmap = self.roadmap_repo.get_roadmap_by_id(
            roadmap_id=roadmap_id,
            user_id=user_id,
        )

        if not roadmap:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Learning roadmap not found",
            )

        safe_update_data = {}

        if "roadmap_title" in update_data:
            safe_update_data["roadmap_title"] = self._limit_text(
                self._to_text(update_data.get("roadmap_title")),
                255,
            )

        if "estimated_duration" in update_data:
            safe_update_data["estimated_duration"] = self._to_text(
                update_data.get("estimated_duration")
            )

        updated_roadmap = self.roadmap_repo.update_roadmap(
            roadmap=roadmap,
            update_data=safe_update_data,
        )

        logger.info(
            "Learning roadmap updated | user_id=%s roadmap_id=%s",
            user_id,
            roadmap_id,
        )

        return self._serialize_roadmap(
            updated_roadmap
        )

    def delete_roadmap(
        self,
        roadmap_id: int,
        user_id: int,
    ) -> Dict[str, str]:
        """
        Delete one roadmap report.
        """

        roadmap = self.roadmap_repo.get_roadmap_by_id(
            roadmap_id=roadmap_id,
            user_id=user_id,
        )

        if not roadmap:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Learning roadmap not found",
            )

        self.roadmap_repo.delete_roadmap(
            roadmap
        )

        logger.info(
            "Learning roadmap deleted | user_id=%s roadmap_id=%s",
            user_id,
            roadmap_id,
        )

        return {
            "message": "Learning roadmap deleted successfully"
        }

    def batch_delete_roadmaps(
        self,
        user_id: int,
        roadmap_ids: List[int],
    ) -> Dict[str, Any]:
        """
        Delete multiple roadmap reports.
        """

        if not roadmap_ids:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="roadmap_ids cannot be empty",
            )

        deleted_count = self.roadmap_repo.batch_delete_roadmaps(
            user_id=user_id,
            roadmap_ids=roadmap_ids,
        )

        logger.info(
            "Batch deleted learning roadmaps | user_id=%s deleted_count=%s",
            user_id,
            deleted_count,
        )

        return {
            "deleted_count": deleted_count,
            "message": f"{deleted_count} learning roadmap(s) deleted successfully",
        }

    def _serialize_roadmap(
        self,
        roadmap,
    ) -> Dict[str, Any]:
        """
        Convert SQLAlchemy model object into API response dictionary.
        """

        return {
            "id": roadmap.id,
            "user_id": roadmap.user_id,
            "resume_id": roadmap.resume_id,
            "target_role": roadmap.target_role,
            "current_skills": roadmap.current_skills,
            "missing_skills": roadmap.missing_skills,
            "roadmap_title": roadmap.roadmap_title,
            "roadmap_summary": roadmap.roadmap_summary,
            "weekly_plan": roadmap.weekly_plan,
            "recommended_projects": roadmap.recommended_projects,
            "recommended_courses": roadmap.recommended_courses,
            "recommended_certifications": roadmap.recommended_certifications,
            "priority_topics": roadmap.priority_topics,
            "estimated_duration": roadmap.estimated_duration,
            "provider": roadmap.provider,
            "model_name": roadmap.model_name,
            "created_at": roadmap.created_at,
            "updated_at": roadmap.updated_at,
        }

    def _to_text(
        self,
        value: Any,
    ) -> str:
        """
        Safely convert LLM output into text for PostgreSQL Text columns.

        Rules:
        - None -> empty string
        - str -> same string
        - list/dict -> pretty JSON string
        - other values -> string conversion
        """

        if value is None:
            return ""

        if isinstance(value, str):
            return value.strip()

        if isinstance(value, (list, dict)):
            return json.dumps(
                value,
                ensure_ascii=False,
                indent=2,
            )

        return str(value).strip()

    def _limit_text(
        self,
        value: Any,
        max_length: int,
    ) -> str:
        """
        Convert value to text and safely limit length for VARCHAR columns.
        """

        text_value = self._to_text(value)

        if len(text_value) <= max_length:
            return text_value

        return text_value[:max_length]