from typing import List

from fastapi import APIRouter
from fastapi import Depends
from fastapi import status
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import get_current_user
from app.schemas.cover_letter import CoverLetterGenerateRequest
from app.schemas.cover_letter import CoverLetterResponse
from app.services.cover_letter_service import CoverLetterService


router = APIRouter()


@router.post(
    "/generate",
    response_model=CoverLetterResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate AI cover letter",
    description="Generate and save a personalized cover letter using resume and job description."
)
def generate_cover_letter_endpoint(
    request: CoverLetterGenerateRequest,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    service = CoverLetterService(db)

    return service.generate_cover_letter(
        user_id=current_user.id,
        resume_id=request.resume_id,
        job_id=request.job_id,
        provider=request.provider,
        model_name=request.model_name
    )


@router.get(
    "/",
    response_model=List[CoverLetterResponse],
    summary="List my cover letters",
    description="Return all cover letters generated by the logged-in user."
)
def list_cover_letters_endpoint(
    skip: int = 0,
    limit: int = 10,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    service = CoverLetterService(db)

    return service.get_my_cover_letters(
        user_id=current_user.id,
        skip=skip,
        limit=limit
    )


@router.get(
    "/{cover_letter_id}",
    response_model=CoverLetterResponse,
    summary="Get cover letter by id",
    description="Return a single cover letter owned by the logged-in user."
)
def get_cover_letter_endpoint(
    cover_letter_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    service = CoverLetterService(db)

    return service.get_cover_letter(
        cover_letter_id=cover_letter_id,
        user_id=current_user.id
    )


@router.delete(
    "/{cover_letter_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete cover letter",
    description="Delete a cover letter owned by the logged-in user."
)
def delete_cover_letter_endpoint(
    cover_letter_id: int,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    service = CoverLetterService(db)

    return service.delete_cover_letter(
        cover_letter_id=cover_letter_id,
        user_id=current_user.id
    )