"""update analysis_reports

Revision ID: 1fa510291e40
Revises: 8e69a302a896
Create Date: 2026-07-27 14:17:38.128700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa510291e40'
down_revision: Union[str, Sequence[str], None] = '8e69a302a896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('analysis_reports', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('analysis_reports', sa.Column('job_description_text', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('extracted_resume_skills', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('extracted_job_skills', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('matched_skills', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('missing_skills', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('recommendations', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'analysis_reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'analysis_reports', 'resumes', ['resume_id'], ['id'])
    op.drop_column('analysis_reports', 'extracted_skills')
    op.drop_column('analysis_reports', 'recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('analysis_reports', sa.Column('extracted_skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analysis_reports', type_='foreignkey')
    op.drop_constraint(None, 'analysis_reports', type_='foreignkey')
    op.drop_column('analysis_reports', 'recommendations')
    op.drop_column('analysis_reports', 'strengths')
    op.drop_column('analysis_reports', 'missing_skills')
    op.drop_column('analysis_reports', 'matched_skills')
    op.drop_column('analysis_reports', 'extracted_job_skills')
    op.drop_column('analysis_reports', 'extracted_resume_skills')
    op.drop_column('analysis_reports', 'job_description_text')
    op.drop_column('analysis_reports', 'resume_id')
    op.drop_column('analysis_reports', 'user_id')
    # ### end Alembic commands ###
