"""create semantic match reports table

Revision ID: 2ef0646fbbd2
Revises: af5e47cc79dc
Create Date: 2026-07-29 12:58:37.633532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ef0646fbbd2'
down_revision: Union[str, Sequence[str], None] = 'af5e47cc79dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_match_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('resume_skills', sa.Text(), nullable=True),
    sa.Column('job_skills', sa.Text(), nullable=True),
    sa.Column('matched_skills', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.Text(), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_match_reports_id'), 'semantic_match_reports', ['id'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_job_id'), 'semantic_match_reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_keyword_score'), 'semantic_match_reports', ['keyword_score'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_overall_score'), 'semantic_match_reports', ['overall_score'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_resume_id'), 'semantic_match_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_semantic_score'), 'semantic_match_reports', ['semantic_score'], unique=False)
    op.create_index(op.f('ix_semantic_match_reports_user_id'), 'semantic_match_reports', ['user_id'], unique=False)
    op.drop_index(op.f('ix_job_recommendation_reports_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_resume_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_target_role'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_user_id'), table_name='job_recommendation_reports')
    op.drop_table('job_recommendation_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recommendation_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resume_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_jobs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('missing_skills_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('job_recommendation_reports_resume_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_recommendation_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_recommendation_reports_pkey'))
    )
    op.create_index(op.f('ix_job_recommendation_reports_user_id'), 'job_recommendation_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_target_role'), 'job_recommendation_reports', ['target_role'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_resume_id'), 'job_recommendation_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_id'), 'job_recommendation_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_semantic_match_reports_user_id'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_semantic_score'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_resume_id'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_overall_score'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_keyword_score'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_job_id'), table_name='semantic_match_reports')
    op.drop_index(op.f('ix_semantic_match_reports_id'), table_name='semantic_match_reports')
    op.drop_table('semantic_match_reports')
    # ### end Alembic commands ###
