"""create ai coverletter table 2

Revision ID: 994f647f44e7
Revises: 1fbccc1c6a14
Create Date: 2026-07-28 17:52:38.001426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994f647f44e7'
down_revision: Union[str, Sequence[str], None] = '1fbccc1c6a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
