"""create pgvector rag tables

Revision ID: bdf4f6a4f419
Revises: da44168921fc
Create Date: 2026-07-30 22:50:57.154074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'bdf4f6a4f419'
down_revision: Union[str, Sequence[str], None] = 'da44168921fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS vector"
    )
    op.create_table('vector_rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=100), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_rag_documents_id'), 'vector_rag_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vector_rag_documents_source_id'), 'vector_rag_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_vector_rag_documents_source_type'), 'vector_rag_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_vector_rag_documents_title'), 'vector_rag_documents', ['title'], unique=False)
    op.create_index(op.f('ix_vector_rag_documents_user_id'), 'vector_rag_documents', ['user_id'], unique=False)
    op.create_table('vector_rag_query_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('matched_chunks', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_rag_query_reports_id'), 'vector_rag_query_reports', ['id'], unique=False)
    op.create_index(op.f('ix_vector_rag_query_reports_user_id'), 'vector_rag_query_reports', ['user_id'], unique=False)
    op.create_table('vector_rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['vector_rag_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_rag_chunks_chunk_index'), 'vector_rag_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_vector_rag_chunks_document_id'), 'vector_rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_rag_chunks_id'), 'vector_rag_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_vector_rag_chunks_user_id'), 'vector_rag_chunks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_job_recommendation_reports_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_resume_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_target_role'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_user_id'), table_name='job_recommendation_reports')
    op.drop_table('job_recommendation_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recommendation_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resume_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_jobs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('missing_skills_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('job_recommendation_reports_resume_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_recommendation_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_recommendation_reports_pkey'))
    )
    op.create_index(op.f('ix_job_recommendation_reports_user_id'), 'job_recommendation_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_target_role'), 'job_recommendation_reports', ['target_role'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_resume_id'), 'job_recommendation_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_id'), 'job_recommendation_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_vector_rag_chunks_user_id'), table_name='vector_rag_chunks')
    op.drop_index(op.f('ix_vector_rag_chunks_id'), table_name='vector_rag_chunks')
    op.drop_index(op.f('ix_vector_rag_chunks_document_id'), table_name='vector_rag_chunks')
    op.drop_index(op.f('ix_vector_rag_chunks_chunk_index'), table_name='vector_rag_chunks')
    op.drop_table('vector_rag_chunks')
    op.drop_index(op.f('ix_vector_rag_query_reports_user_id'), table_name='vector_rag_query_reports')
    op.drop_index(op.f('ix_vector_rag_query_reports_id'), table_name='vector_rag_query_reports')
    op.drop_table('vector_rag_query_reports')
    op.drop_index(op.f('ix_vector_rag_documents_user_id'), table_name='vector_rag_documents')
    op.drop_index(op.f('ix_vector_rag_documents_title'), table_name='vector_rag_documents')
    op.drop_index(op.f('ix_vector_rag_documents_source_type'), table_name='vector_rag_documents')
    op.drop_index(op.f('ix_vector_rag_documents_source_id'), table_name='vector_rag_documents')
    op.drop_index(op.f('ix_vector_rag_documents_id'), table_name='vector_rag_documents')
    op.drop_table('vector_rag_documents')
    # ### end Alembic commands ###
