"""create rag tables

Revision ID: da44168921fc
Revises: 612efa6dc47c
Create Date: 2026-07-29 16:15:28.836884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da44168921fc'
down_revision: Union[str, Sequence[str], None] = '612efa6dc47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_recommendation_reports_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_resume_id'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_target_role'), table_name='job_recommendation_reports')
    op.drop_index(op.f('ix_job_recommendation_reports_user_id'), table_name='job_recommendation_reports')
    op.drop_table('job_recommendation_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recommendation_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resume_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_jobs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('missing_skills_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('job_recommendation_reports_resume_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_recommendation_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_recommendation_reports_pkey'))
    )
    op.create_index(op.f('ix_job_recommendation_reports_user_id'), 'job_recommendation_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_target_role'), 'job_recommendation_reports', ['target_role'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_resume_id'), 'job_recommendation_reports', ['resume_id'], unique=False)
    op.create_index(op.f('ix_job_recommendation_reports_id'), 'job_recommendation_reports', ['id'], unique=False)
    # ### end Alembic commands ###
